// Code generated by protoc-gen-go.
// source: gopio.proto
// DO NOT EDIT!

/*
Package gopio is a generated protocol buffer package.

It is generated from these files:
	gopio.proto

It has these top-level messages:
	Pin
	PinDirection
	PinState
	PinPull
*/
package gopio

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pin struct {
	Number int32 `protobuf:"varint,1,opt,name=Number" json:"Number,omitempty"`
}

func (m *Pin) Reset()                    { *m = Pin{} }
func (m *Pin) String() string            { return proto.CompactTextString(m) }
func (*Pin) ProtoMessage()               {}
func (*Pin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Pin) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type PinDirection struct {
	Direction int32 `protobuf:"varint,1,opt,name=Direction" json:"Direction,omitempty"`
}

func (m *PinDirection) Reset()                    { *m = PinDirection{} }
func (m *PinDirection) String() string            { return proto.CompactTextString(m) }
func (*PinDirection) ProtoMessage()               {}
func (*PinDirection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PinDirection) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

type PinState struct {
	State int32 `protobuf:"varint,1,opt,name=State" json:"State,omitempty"`
}

func (m *PinState) Reset()                    { *m = PinState{} }
func (m *PinState) String() string            { return proto.CompactTextString(m) }
func (*PinState) ProtoMessage()               {}
func (*PinState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PinState) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

type PinPull struct {
	Pull int32 `protobuf:"varint,1,opt,name=Pull" json:"Pull,omitempty"`
}

func (m *PinPull) Reset()                    { *m = PinPull{} }
func (m *PinPull) String() string            { return proto.CompactTextString(m) }
func (*PinPull) ProtoMessage()               {}
func (*PinPull) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PinPull) GetPull() int32 {
	if m != nil {
		return m.Pull
	}
	return 0
}

func init() {
	proto.RegisterType((*Pin)(nil), "gopio.Pin")
	proto.RegisterType((*PinDirection)(nil), "gopio.PinDirection")
	proto.RegisterType((*PinState)(nil), "gopio.PinState")
	proto.RegisterType((*PinPull)(nil), "gopio.PinPull")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GoPIO service

type GoPIOClient interface {
	// Is the Pin input or output?
	GetPinDirection(ctx context.Context, in *Pin, opts ...grpc.CallOption) (*PinDirection, error)
	// Is the Pin High or Low
	GetPinState(ctx context.Context, in *Pin, opts ...grpc.CallOption) (*PinState, error)
	// Is the Pin Off, Down or Up
	GetPinPull(ctx context.Context, in *Pin, opts ...grpc.CallOption) (*PinPull, error)
	// Set the Pin input or output?
	SetPinDirection(ctx context.Context, in *Pin, opts ...grpc.CallOption) (*PinDirection, error)
	// Is the Pin High or Low
	SetPinState(ctx context.Context, in *Pin, opts ...grpc.CallOption) (*PinState, error)
	// Is the Pin Off, Down or Up
	SetPinPull(ctx context.Context, in *Pin, opts ...grpc.CallOption) (*PinPull, error)
}

type goPIOClient struct {
	cc *grpc.ClientConn
}

func NewGoPIOClient(cc *grpc.ClientConn) GoPIOClient {
	return &goPIOClient{cc}
}

func (c *goPIOClient) GetPinDirection(ctx context.Context, in *Pin, opts ...grpc.CallOption) (*PinDirection, error) {
	out := new(PinDirection)
	err := grpc.Invoke(ctx, "/gopio.GoPIO/GetPinDirection", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goPIOClient) GetPinState(ctx context.Context, in *Pin, opts ...grpc.CallOption) (*PinState, error) {
	out := new(PinState)
	err := grpc.Invoke(ctx, "/gopio.GoPIO/GetPinState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goPIOClient) GetPinPull(ctx context.Context, in *Pin, opts ...grpc.CallOption) (*PinPull, error) {
	out := new(PinPull)
	err := grpc.Invoke(ctx, "/gopio.GoPIO/GetPinPull", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goPIOClient) SetPinDirection(ctx context.Context, in *Pin, opts ...grpc.CallOption) (*PinDirection, error) {
	out := new(PinDirection)
	err := grpc.Invoke(ctx, "/gopio.GoPIO/SetPinDirection", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goPIOClient) SetPinState(ctx context.Context, in *Pin, opts ...grpc.CallOption) (*PinState, error) {
	out := new(PinState)
	err := grpc.Invoke(ctx, "/gopio.GoPIO/SetPinState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goPIOClient) SetPinPull(ctx context.Context, in *Pin, opts ...grpc.CallOption) (*PinPull, error) {
	out := new(PinPull)
	err := grpc.Invoke(ctx, "/gopio.GoPIO/SetPinPull", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GoPIO service

type GoPIOServer interface {
	// Is the Pin input or output?
	GetPinDirection(context.Context, *Pin) (*PinDirection, error)
	// Is the Pin High or Low
	GetPinState(context.Context, *Pin) (*PinState, error)
	// Is the Pin Off, Down or Up
	GetPinPull(context.Context, *Pin) (*PinPull, error)
	// Set the Pin input or output?
	SetPinDirection(context.Context, *Pin) (*PinDirection, error)
	// Is the Pin High or Low
	SetPinState(context.Context, *Pin) (*PinState, error)
	// Is the Pin Off, Down or Up
	SetPinPull(context.Context, *Pin) (*PinPull, error)
}

func RegisterGoPIOServer(s *grpc.Server, srv GoPIOServer) {
	s.RegisterService(&_GoPIO_serviceDesc, srv)
}

func _GoPIO_GetPinDirection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoPIOServer).GetPinDirection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopio.GoPIO/GetPinDirection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoPIOServer).GetPinDirection(ctx, req.(*Pin))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoPIO_GetPinState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoPIOServer).GetPinState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopio.GoPIO/GetPinState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoPIOServer).GetPinState(ctx, req.(*Pin))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoPIO_GetPinPull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoPIOServer).GetPinPull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopio.GoPIO/GetPinPull",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoPIOServer).GetPinPull(ctx, req.(*Pin))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoPIO_SetPinDirection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoPIOServer).SetPinDirection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopio.GoPIO/SetPinDirection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoPIOServer).SetPinDirection(ctx, req.(*Pin))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoPIO_SetPinState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoPIOServer).SetPinState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopio.GoPIO/SetPinState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoPIOServer).SetPinState(ctx, req.(*Pin))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoPIO_SetPinPull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoPIOServer).SetPinPull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopio.GoPIO/SetPinPull",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoPIOServer).SetPinPull(ctx, req.(*Pin))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoPIO_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gopio.GoPIO",
	HandlerType: (*GoPIOServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPinDirection",
			Handler:    _GoPIO_GetPinDirection_Handler,
		},
		{
			MethodName: "GetPinState",
			Handler:    _GoPIO_GetPinState_Handler,
		},
		{
			MethodName: "GetPinPull",
			Handler:    _GoPIO_GetPinPull_Handler,
		},
		{
			MethodName: "SetPinDirection",
			Handler:    _GoPIO_SetPinDirection_Handler,
		},
		{
			MethodName: "SetPinState",
			Handler:    _GoPIO_SetPinState_Handler,
		},
		{
			MethodName: "SetPinPull",
			Handler:    _GoPIO_SetPinPull_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gopio.proto",
}

func init() { proto.RegisterFile("gopio.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x13, 0x35, 0x55, 0x5f, 0xc5, 0xc2, 0x28, 0x52, 0xc4, 0x42, 0x59, 0x2f, 0x22, 0x25,
	0x07, 0xf5, 0x17, 0x14, 0xa1, 0x78, 0xd1, 0xc5, 0xfc, 0x82, 0x36, 0x86, 0x3a, 0xd0, 0xcc, 0x96,
	0xb0, 0xfd, 0x4d, 0xfe, 0x4d, 0xc9, 0x4e, 0x70, 0xe3, 0x4d, 0x7b, 0xda, 0xf7, 0x76, 0xde, 0xf0,
	0x3e, 0x76, 0x31, 0x5c, 0xbb, 0x2d, 0xbb, 0x7c, 0xdb, 0x38, 0xef, 0x28, 0x0b, 0xc6, 0x4c, 0x70,
	0x68, 0x59, 0xe8, 0x0a, 0x83, 0xd7, 0x5d, 0xbd, 0xaa, 0x9a, 0x71, 0x3a, 0x4d, 0xef, 0xb2, 0xf7,
	0xce, 0x99, 0x19, 0xce, 0x2c, 0xcb, 0x33, 0x37, 0x55, 0xe9, 0xd9, 0x09, 0xdd, 0xe0, 0xf4, 0xc7,
	0x74, 0xd1, 0x78, 0x61, 0xa6, 0x38, 0xb1, 0x2c, 0x85, 0x5f, 0xfa, 0x8a, 0x2e, 0x91, 0x05, 0xd1,
	0xa5, 0xd4, 0x98, 0x09, 0x8e, 0x2d, 0x8b, 0xdd, 0x6d, 0x36, 0x44, 0x38, 0x6a, 0xcf, 0x6e, 0x1e,
	0xf4, 0xc3, 0xd7, 0x01, 0xb2, 0x85, 0xb3, 0x2f, 0x6f, 0xf4, 0x84, 0xd1, 0xa2, 0xf2, 0xbf, 0xba,
	0x91, 0x2b, 0xbf, 0x65, 0xb9, 0xbe, 0x88, 0x3a, 0xd6, 0x27, 0x34, 0xc3, 0x50, 0xb7, 0x94, 0xa1,
	0xbf, 0x31, 0x8a, 0x5a, 0x51, 0x12, 0xba, 0x07, 0x34, 0x1d, 0x78, 0xfa, 0xe1, 0xf3, 0xa8, 0xdb,
	0x99, 0x49, 0x5a, 0x9e, 0x62, 0x2f, 0x9e, 0xe2, 0x5f, 0x3c, 0xc5, 0x1f, 0x79, 0xe6, 0xb7, 0x18,
	0x97, 0xae, 0xce, 0x6b, 0xfe, 0x10, 0x5e, 0x7f, 0xfa, 0xd2, 0x49, 0xbd, 0x14, 0x4d, 0xcd, 0xf5,
	0x09, 0x6d, 0xba, 0x1a, 0x84, 0xaf, 0x7e, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x10, 0xb9, 0xa0,
	0xff, 0xf9, 0x01, 0x00, 0x00,
}
